name: E2E Tests & Update Web Service
on:
   # Run on any commit to the #master branch
   push:
      branches: [master]
   # Run on pull requests into the #master branch
   pull_request:
      branches: [master]
   # Allows user to trigger the workflow from GitHub's web UI
   workflow_dispatch:

jobs:
   e2etests:
      name: Test
      runs-on: ubuntu-latest
      strategy:
         matrix:
            include:
               - branch: develop
                 webpack: dev
               - branch: master
                 webpack: update
      steps:
         - uses: actions/checkout@v3
           with:
              path: ab_platform_web
              submodules: true

         - uses: actions/checkout@v3
           with:
              path: web
              repository: digi-serve/ab_service_web

         - uses: actions/checkout@v3
           with:
              path: api_sails
              repository: digi-serve/ab_service_api_sails

         - run: npm i
           working-directory: ./ab_platform_web

         - name: Webpack
           run: npm run build:${{ matrix.webpack }}
           working-directory: ./ab_platform_web

        # webpack expects the folder to be called "web" ab-install action expects "ab_service_web"
         - run: mv web ab_service_web
         - run: mv api_sails ab_service_api_sails

         - uses: digi-serve/ab-install-action@platform_web
           with:
              port: 8080
              folder: ab

         - name: Check out kitchen-sink tests
           uses: actions/checkout@v2
           with:
              repository: digi-serve/kitchensink_app
              path: ab/test/e2e/cypress/integration/kitchensink_app

         - name: Run Cypress Tests
           uses: cypress-io/github-action@v2
           with:
              working-directory: ./ab
              project: ./test/e2e
              config: baseUrl=http://localhost:8080,responseTimeout=100000,defaultCommandTimeout=24000,retries=2
              wait-on: "http://localhost:8080"
              wait-on-timeout: 300
              env: stack=ab
              install: false

         - uses: actions/upload-artifact@v2
           if: failure()
           with:
              name: cypress-screenshots
              path: ./ab/test/e2e/cypress/screenshots

   # if its a push event and tests passed update ab_service_web
   update_ab_service_web:
      name: Update ab_service_web
      needs: e2etests
      if: ${{ github.event_name == 'push' }}
      runs-on: ubuntu-latest
      strategy:
         matrix:
            include:
               - branch: develop
                 webpack: dev
               - branch: master
                 webpack: update
      steps:
         - uses: actions/checkout@v3
           with:
              path: ab_platform_web
              submodules: true
         - uses: actions/checkout@v3
           with:
              path: web
              repository: digi-serve/ab_service_web
              ref: ${{ matrix.branch }}
              token: ${{ secrets.DS_REPO_PAT }}
         - uses: actions/checkout@v3
           with:
              path: api_sails
              repository: digi-serve/ab_service_api_sails
              ref: ${{ matrix.branch }}
              token: ${{ secrets.DS_REPO_PAT }}
         - run: npm i
           working-directory: ./ab_platform_web
         - run: npm run build:${{ matrix.webpack }}
           working-directory: ./ab_platform_web
         - uses: EndBug/add-and-commit@v9
           with:
              cwd: ./web
         - uses: EndBug/add-and-commit@v9
           with:
              cwd: ./api_sails
